name: night_lofi
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.3.3
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6

  flutter_spinkit: ^5.1.0
  flutter_riverpod: ^2.1.1
  sensors_plus: ^2.0.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/background_images/
    - assets/logo/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          style: normal
        - asset: fonts/Inter-SemiBold.ttf
          weight: 500
        - asset: fonts/Inter-Bold.ttf
          weight: 600
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 700
